import type { NewsArticle, AppEvent, Member, Resource, RugEncyclopediaEntry, BoardMember } from './types';

export const newsData: NewsArticle[] = [
  {
    id: '1',
    title: 'PCMEA Announces Annual Design Awards',
    source: 'PCMEA Official',
    date: '2024-07-15',
    excerpt: 'The Pakistan Carpet Manufacturers and Exporters Association is proud to announce the annual carpet design awards to celebrate innovation and creativity in the industry.',
    content: 'The Pakistan Carpet Manufacturers and Exporters Association (PCMEA) has officially opened submissions for its prestigious Annual Design Awards. This event aims to recognize and celebrate the outstanding creativity and innovation within the Pakistani carpet industry. Designers and manufacturers are invited to submit their best works from the past year. The awards will be judged by a panel of international design experts, and winners will be announced at a grand ceremony in October. This initiative is part of PCMEA\'s ongoing commitment to fostering excellence and promoting Pakistani craftsmanship on the global stage.',
    imageUrl: 'https://picsum.photos/600/400',
    category: 'PCMEA Announcements',
  },
  {
    id: '2',
    title: 'Global Market Trends for Handmade Carpets',
    source: 'Trade Chronicle',
    date: '2024-07-12',
    excerpt: 'A new report indicates a rising demand for sustainably sourced and handmade carpets in European and North American markets.',
    content: 'A recent report published by the International Trade Monitor highlights a significant shift in consumer preferences in the global carpet market. There is a growing demand for handmade, sustainably sourced carpets, particularly in European and North American markets. The report attributes this trend to increasing consumer awareness about ethical production and environmental impact. This presents a unique opportunity for Pakistani exporters who specialize in traditional, eco-friendly weaving techniques. The report suggests that producers who emphasize sustainability in their marketing can gain a competitive edge.',
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Market Analysis',
  },
  {
    id: '3',
    title: 'Export Facilitation Seminar Held in Lahore',
    source: 'Business Recorder',
    date: '2024-07-10',
    excerpt: 'A seminar aimed at educating exporters on new international trade regulations was successfully held, with over 100 members in attendance.',
    content: 'Over 100 members of PCMEA attended a crucial seminar on export facilitation held at the PCMEA head office in Lahore. The seminar focused on navigating the complexities of new international trade regulations, including updated EU compliance standards and US customs requirements. Guest speakers from the Ministry of Commerce and international logistics firms provided valuable insights and answered questions from the attendees. The event was part of PCMEA\'s continuous efforts to empower its members with the knowledge needed to thrive in the international market.',
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Industry Trends',
  },
  {
    id: '4',
    title: 'New Weaving Techniques Workshop',
    source: 'PCMEA Training Wing',
    date: '2024-07-08',
    excerpt: 'PCMEA is organizing a hands-on workshop to train artisans on new-age weaving techniques that blend traditional patterns with modern aesthetics.',
    content: 'The PCMEA Training Wing has announced a three-day, hands-on workshop for artisans focused on innovative weaving techniques. The workshop aims to bridge the gap between traditional craftsmanship and modern design trends. Participants will learn how to incorporate contemporary color palettes and abstract patterns into classic weaving styles. This initiative seeks to enhance the skill set of local artisans, making their products more appealing to a younger, design-conscious international audience. The workshop will be held in Karachi and is free for all PCMEA member artisans.',
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Training Materials',
  },
];

export const eventsData: AppEvent[] = [
  {
    id: '1',
    title: 'Annual General Meeting',
    date: new Date('2024-08-20T10:00:00'),
    location: 'PCMEA Head Office, Lahore',
    description: 'The Annual General Meeting for all PCMEA members.',
  },
  {
    id: '2',
    title: 'DOMOTEX Trade Fair',
    date: new Date('2024-09-05T09:00:00'),
    location: 'Hannover, Germany',
    description: 'International trade fair for carpets and floor coverings.',
  },
  {
    id: '3',
    title: 'Export Documentation Workshop',
    date: new Date('2024-09-18T11:00:00'),
    location: 'Online Webinar',
    description: 'A workshop covering all aspects of export documentation.',
  },
  {
    id: '4',
    title: 'Carpet Weaving Exhibition',
    date: new Date('2024-10-10T10:00:00'),
    location: 'Expo Centre, Karachi',
    description: 'A national exhibition showcasing the finest handmade carpets.',
  },
];

export const memberData: Member[] = [
  // A
  {
    id: '2',
    name: 'Fatima Ali',
    company: 'Ali Rugs & Co.',
    companyLogoUrl: 'https://picsum.photos/120/120?random=12',
    phone: '+92 333 7654321',
    email: 'fatima.ali@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=2',
    bio: 'Fatima founded Ali Rugs & Co. with a vision to empower female artisans in rural areas. The company specializes in vegetable-dyed, hand-knotted carpets with intricate floral patterns.',
    specialties: ['Hand-knotted', 'Vegetable Dyes', 'Social Enterprise'],
  },
  {
    id: '6',
    name: 'Abdullah Qureshi',
    company: 'Antique Carpet Creations',
    companyLogoUrl: 'https://picsum.photos/120/120?random=16',
    phone: '+92 301 2233445',
    email: 'abdullah.q@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=6',
    bio: 'Specializing in recreating classic antique designs with a modern twist. Our carpets bring historical elegance to contemporary homes.',
    specialties: ['Antique Reproduction', 'Persian Designs', 'Custom Sizing'],
  },
  {
    id: '7',
    name: 'Amina Baig',
    company: 'Artisan Weavers Guild',
    companyLogoUrl: 'https://picsum.photos/120/120?random=17',
    phone: '+92 302 3344556',
    email: 'amina.baig@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=7',
    bio: 'A cooperative of artisans dedicated to preserving traditional weaving techniques and providing fair trade prices for their craft.',
    specialties: ['Fair Trade', 'Traditional Techniques', 'Community Focused'],
  },
  {
    id: '8',
    name: 'Asif Mehmood',
    company: 'Atlas Exporters',
    companyLogoUrl: 'https://picsum.photos/120/120?random=18',
    phone: '+92 303 4455667',
    email: 'asif.m@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=8',
    bio: 'A leading exporter of hand-knotted carpets to the Middle East and North Africa. Known for reliability and quality.',
    specialties: ['MENA Market', 'Bulk Orders', 'Logistics'],
  },
  {
    id: '9',
    name: 'Anila Zafar',
    company: 'Azure Fine Rugs',
    companyLogoUrl: 'https://picsum.photos/120/120?random=19',
    phone: '+92 304 5566778',
    email: 'anila.zafar@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=9',
    bio: 'Specializing in modern and contemporary designs with a focus on unique color palettes, particularly shades of blue and green.',
    specialties: ['Contemporary Design', 'Color Theory', 'Interior Design Collaboration'],
  },
  // B
  {
    id: '5',
    name: 'Bilal Hassan',
    company: 'Hassan Fine Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=15',
    phone: '+92 312 4455667',
    email: 'bilal.hassan@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=5',
    bio: 'Bilal specializes in the restoration and trade of antique and vintage Pakistani rugs. His collection includes rare pieces from the early 20th century.',
    specialties: ['Antique Rugs', 'Restoration', 'Carpet History'],
  },
  {
    id: '10',
    name: 'Babar Malik',
    company: 'Baloch Traditions',
    companyLogoUrl: 'https://picsum.photos/120/120?random=20',
    phone: '+92 313 6677889',
    email: 'babar.malik@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=10',
    bio: 'Dedicated to the promotion and export of traditional Balochi rugs, known for their distinctive geometric patterns and dark, rich colors.',
    specialties: ['Balochi Rugs', 'Tribal Designs', 'Natural Dyes'],
  },
  {
    id: '11',
    name: 'Beenish Khan',
    company: 'Bokhara Palace',
    companyLogoUrl: 'https://picsum.photos/120/120?random=21',
    phone: '+92 314 7788990',
    email: 'beenish.k@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=11',
    bio: 'Exclusively focused on the production and export of high-quality Mori Bokhara rugs, a staple of Pakistani carpet weaving.',
    specialties: ['Mori Bokhara', 'Fine Wool', 'Global Shipping'],
  },
  {
    id: '12',
    name: 'Burhan Ahmed',
    company: 'Builders Choice Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=22',
    phone: '+92 315 8899001',
    email: 'burhan.ahmed@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=12',
    bio: 'We supply durable and beautiful hand-woven carpets for large-scale construction projects, including hotels and offices.',
    specialties: ['Contract Weaving', 'Hospitality', 'Commercial Projects'],
  },
  {
    id: '13',
    name: 'Bushra Anwar',
    company: 'Bespoke Weaves',
    companyLogoUrl: 'https://picsum.photos/120/120?random=23',
    phone: '+92 316 9900112',
    email: 'bushra.anwar@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=13',
    bio: 'Creating custom, one-of-a-kind carpets for discerning clients. From design conception to final product, we make your vision a reality.',
    specialties: ['Custom Design', 'Bespoke Rugs', 'Client Collaboration'],
  },
  // C
  {
    id: '4',
    name: 'Aisha Choudhry',
    company: 'Choudhry Weavers',
    companyLogoUrl: 'https://picsum.photos/120/120?random=14',
    phone: '+92 345 1122334',
    email: 'aisha.c@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=4',
    bio: 'Aisha is an award-winning designer who blends contemporary art with traditional weaving. Her work has been featured in international design magazines.',
    specialties: ['Contemporary Art', 'Bespoke Rugs', 'Designer Collaborations'],
  },
  {
    id: '14',
    name: 'Chaudhry Kamal',
    company: 'City Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=24',
    phone: '+92 321 1234567',
    email: 'kamal.c@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=14',
    bio: 'A major wholesale supplier for the domestic Pakistani market, with showrooms in Lahore, Karachi, and Islamabad.',
    specialties: ['Wholesale', 'Domestic Market', 'Retail Partnerships'],
  },
  {
    id: '15',
    name: 'Cyrus Mehta',
    company: 'Colonial Rugs',
    companyLogoUrl: 'https://picsum.photos/120/120?random=25',
    phone: '+92 322 2345678',
    email: 'cyrus.mehta@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=15',
    bio: 'Specializing in the reproduction of rug designs from the British colonial era, known for their unique blend of Eastern and Western aesthetics.',
    specialties: ['Colonial Designs', 'Historical Rugs', 'UK Market'],
  },
  {
    id: '16',
    name: 'Celine D’Souza',
    company: 'Creative Looms Pakistan',
    companyLogoUrl: 'https://picsum.photos/120/120?random=26',
    phone: '+92 323 3456789',
    email: 'celine.d@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=16',
    bio: 'An innovative company that experiments with non-traditional materials and designs, pushing the boundaries of carpet weaving.',
    specialties: ['Innovative Materials', 'Modern Art', 'Experimental Design'],
  },
  {
    id: '17',
    name: 'Chand Bibi',
    company: 'Crescent Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=27',
    phone: '+92 324 4567890',
    email: 'chand.bibi@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=17',
    bio: 'A family-run business for over 50 years, Crescent Carpets is known for its consistent quality and classic designs.',
    specialties: ['Family Business', 'Classic Designs', 'Quality Assurance'],
  },
  // D
  {
    id: '18',
    name: 'Danish Akram',
    company: 'Diamond Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=28',
    phone: '+92 331 5678901',
    email: 'danish.akram@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=18',
    bio: 'Producers of high-knot-count, luxury silk-on-silk carpets for the high-end market. Each piece is a work of art.',
    specialties: ['Silk on Silk', 'High Knot Count', 'Luxury Market'],
  },
  {
    id: '19',
    name: 'Durdana Shah',
    company: 'Durable Weaves Inc.',
    companyLogoUrl: 'https://picsum.photos/120/120?random=29',
    phone: '+92 332 6789012',
    email: 'durdana.shah@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=19',
    bio: 'We focus on creating highly durable carpets for high-traffic areas without compromising on design and beauty.',
    specialties: ['Durability', 'High-Traffic Rugs', 'Commercial Spaces'],
  },
  {
    id: '20',
    name: 'Dawood Ibrahim',
    company: 'Dynasty Rugs',
    companyLogoUrl: 'https://picsum.photos/120/120?random=30',
    phone: '+92 333 7890123',
    email: 'dawood.i@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=20',
    bio: 'Exporters of fine Pakistani carpets to East Asia, with a strong presence in Japan and South Korea.',
    specialties: ['East Asian Market', 'Cultural Designs', 'Export Partnership'],
  },
  {
    id: '21',
    name: 'Dilawar Hussain',
    company: 'Dastkaar Looms',
    companyLogoUrl: 'https://picsum.photos/120/120?random=31',
    phone: '+92 334 8901234',
    email: 'dilawar.h@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=21',
    bio: 'Working directly with master artisans (Dastkaars) to bring their unique creations to the global market.',
    specialties: ['Master Artisans', 'Unique Pieces', 'Direct Sourcing'],
  },
  {
    id: '22',
    name: 'Deena Rahman',
    company: 'Designers Choice',
    companyLogoUrl: 'https://picsum.photos/120/120?random=32',
    phone: '+92 335 9012345',
    email: 'deena.rahman@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=22',
    bio: 'A favorite supplier for interior designers, offering a curated collection of contemporary and transitional rugs.',
    specialties: ['Interior Design', 'Transitional Rugs', 'Curated Collections'],
  },
  // E
  {
    id: '23',
    name: 'Ehsan Ullah',
    company: 'Eastern Exports',
    companyLogoUrl: 'https://picsum.photos/120/120?random=33',
    phone: '+92 341 1122334',
    email: 'ehsan.ullah@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=23',
    bio: 'A well-established name in the export business, with a history of providing quality and service for over 30 years.',
    specialties: ['Established Exporter', 'Global Network', 'Reliability'],
  },
  {
    id: '24',
    name: 'Ejaz Bhatti',
    company: 'Elegant Carpets Ltd.',
    companyLogoUrl: 'https://picsum.photos/120/120?random=34',
    phone: '+92 342 2233445',
    email: 'ejaz.bhatti@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=24',
    bio: 'Producers of finely woven carpets with elegant floral designs, perfect for formal living spaces.',
    specialties: ['Floral Designs', 'Fine Weaving', 'Formal Rugs'],
  },
  {
    id: '25',
    name: 'Erum Sheikh',
    company: 'Empire Trading',
    companyLogoUrl: 'https://picsum.photos/120/120?random=35',
    phone: '+92 343 3344556',
    email: 'erum.sheikh@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=25',
    bio: 'A large-scale trading house dealing in a wide variety of carpet types, from hand-knotted to machine-made.',
    specialties: ['Trading House', 'Variety', 'Volume Orders'],
  },
  {
    id: '26',
    name: 'Ehsan Elahi',
    company: 'Elite Weavers',
    companyLogoUrl: 'https://picsum.photos/120/120?random=36',
    phone: '+92 344 4455667',
    email: 'ehsan.elahi@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=26',
    bio: 'A boutique firm that produces a limited number of exquisite, high-end carpets each year for collectors.',
    specialties: ['Boutique Firm', 'Collectors Items', 'Exquisite Quality'],
  },
  {
    id: '27',
    name: 'Esha Khan',
    company: 'Evergreen Looms',
    companyLogoUrl: 'https://picsum.photos/120/120?random=37',
    phone: '+92 345 5566778',
    email: 'esha.khan@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=27',
    bio: 'Focused on sustainable and eco-friendly production, using only natural dyes and ethically sourced wool.',
    specialties: ['Sustainability', 'Eco-Friendly', 'Natural Dyes'],
  },
  // F
  {
    id: '28',
    name: 'Faizan Mustafa',
    company: 'Fine Weave Exports',
    companyLogoUrl: 'https://picsum.photos/120/120?random=38',
    phone: '+92 300 1112222',
    email: 'faizan.m@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=28',
    bio: 'Exporters of premium quality hand-knotted rugs with a focus on intricate designs and superior craftsmanship.',
    specialties: ['Premium Quality', 'Intricate Designs', 'Global Exports'],
  },
  {
    id: '29',
    name: 'Feroze Khan',
    company: 'Frontier Rugs',
    companyLogoUrl: 'https://picsum.photos/120/120?random=39',
    phone: '+92 301 2223333',
    email: 'feroze.k@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=29',
    bio: 'Specializing in tribal and nomadic rugs from the frontier regions of Pakistan, known for their rustic charm.',
    specialties: ['Tribal Rugs', 'Nomadic Designs', 'Rustic Charm'],
  },
  // G
  {
    id: '30',
    name: 'Gul Ahmed',
    company: 'Gul Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=40',
    phone: '+92 302 3334444',
    email: 'gul.ahmed@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=30',
    bio: 'A household name in Pakistan, Gul Carpets offers a wide range of machine-made and hand-knotted rugs for every budget.',
    specialties: ['Machine-Made', 'Retail Chain', 'Affordable Luxury'],
  },
  {
    id: '31',
    name: 'Gohar Rasheed',
    company: 'Gandhara Looms',
    companyLogoUrl: 'https://picsum.photos/120/120?random=41',
    phone: '+92 303 4445555',
    email: 'gohar.r@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=31',
    bio: 'Inspired by the ancient Gandhara civilization, our rugs feature unique motifs and a palette drawn from historical artifacts.',
    specialties: ['Historical Designs', 'Gandhara Art', 'Unique Motifs'],
  },
  // H
  {
    id: '32',
    name: 'Haris Qadeer',
    company: 'Heritage Weavers',
    companyLogoUrl: 'https://picsum.photos/120/120?random=42',
    phone: '+92 304 5556666',
    email: 'haris.q@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=32',
    bio: 'Dedicated to preserving the weaving heritage of Pakistan by employing traditional techniques passed down through generations.',
    specialties: ['Heritage Techniques', 'Generational Weavers', 'Cultural Preservation'],
  },
  {
    id: '33',
    name: 'Hina Rabbani',
    company: 'HR Collections',
    companyLogoUrl: 'https://picsum.photos/120/120?random=43',
    phone: '+92 305 6667777',
    email: 'hina.r@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=33',
    bio: 'A designer-led brand creating contemporary rugs that are both functional art pieces and luxurious floor coverings.',
    specialties: ['Designer Rugs', 'Contemporary Art', 'Luxury Flooring'],
  },
  // I
  {
    id: '34',
    name: 'Imran Abbas',
    company: 'Indus Valley Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=44',
    phone: '+92 306 7778888',
    email: 'imran.abbas@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=34',
    bio: 'Drawing inspiration from the ancient Indus Valley civilization, we create rugs with unique geometric and symbolic patterns.',
    specialties: ['Indus Valley Designs', 'Geometric Patterns', 'Symbolic Art'],
  },
  {
    id: '35',
    name: 'Iqbal Hussain',
    company: 'Iqbal & Sons',
    companyLogoUrl: 'https://picsum.photos/120/120?random=45',
    phone: '+92 307 8889999',
    email: 'iqbal.h@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=35',
    bio: 'A family business with a 60-year history of excellence in producing high-quality traditional Pakistani carpets.',
    specialties: ['Family Legacy', 'Traditional Carpets', 'Decades of Experience'],
  },
  // J
  {
    id: '36',
    name: 'Junaid Khan',
    company: 'J.K. Exporters',
    companyLogoUrl: 'https://picsum.photos/120/120?random=46',
    phone: '+92 308 9990000',
    email: 'junaid.k@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=36',
    bio: 'A leading exporter of Chobi and Ziegler rugs, known for our expertise in natural dyeing and antique finishing techniques.',
    specialties: ['Chobi Rugs', 'Ziegler Designs', 'Natural Dyeing'],
  },
  {
    id: '37',
    name: 'Jamal Shah',
    company: 'Jewel of the East',
    companyLogoUrl: 'https://picsum.photos/120/120?random=47',
    phone: '+92 309 1110000',
    email: 'jamal.shah@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=37',
    bio: 'We produce exquisite silk carpets that are true "jewels," featuring intricate details and a luminous sheen.',
    specialties: ['Silk Carpets', 'Exquisite Details', 'Luminous Sheen'],
  },
  // K
  {
    id: '1',
    name: 'Ahmed Khan',
    company: 'Khan Carpets International',
    companyLogoUrl: 'https://picsum.photos/120/120?random=11',
    phone: '+92 300 1234567',
    email: 'ahmed.khan@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=1',
    bio: 'Ahmed is a third-generation carpet exporter with a focus on modernizing traditional Pakistani designs for a global audience. His company is known for its high-quality wool and silk carpets.',
    specialties: ['Modern Design', 'Silk Rugs', 'EU Market'],
  },
  // L
  {
    id: '38',
    name: 'Laila Mirza',
    company: 'Lahore Carpet Company',
    companyLogoUrl: 'https://picsum.photos/120/120?random=48',
    phone: '+92 310 2221111',
    email: 'laila.m@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=38',
    bio: 'Based in the heart of Lahore, we specialize in reproducing intricate Mughal-era designs with exceptional detail.',
    specialties: ['Mughal Designs', 'Lahori Weaving', 'Historical Accuracy'],
  },
  {
    id: '39',
    name: 'Liaqat Ali',
    company: 'Looms of Punjab',
    companyLogoUrl: 'https://picsum.photos/120/120?random=49',
    phone: '+92 311 3332222',
    email: 'liaqat.ali@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=39',
    bio: 'A collective of weavers from across Punjab, producing a diverse range of rugs that reflect the region\'s rich culture.',
    specialties: ['Punjabi Culture', 'Weaver Collective', 'Diverse Range'],
  },
  // M
  {
    id: '3',
    name: 'Usman Malik',
    company: 'Malik Exporters',
    companyLogoUrl: 'https://picsum.photos/120/120?random=13',
    phone: '+92 321 9876543',
    email: 'usman.malik@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=3',
    bio: 'With over 20 years in the business, Usman is an expert in logistics and large-scale exports. Malik Exporters is a leading supplier to major retail chains in North America.',
    specialties: ['Large-scale Export', 'Logistics', 'US Market'],
  },
  {
    id: '40',
    name: 'Mariam Ansari',
    company: 'Modern Weaves',
    companyLogoUrl: 'https://picsum.photos/120/120?random=50',
    phone: '+92 312 4443333',
    email: 'mariam.a@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=40',
    bio: 'Pioneers in minimalist and abstract rug designs, catering to the modern interior design market worldwide.',
    specialties: ['Minimalist Design', 'Abstract Rugs', 'Modern Interiors'],
  },
  // N
  {
    id: '41',
    name: 'Nadia Hussain',
    company: 'Nomad Carpet Ventures',
    companyLogoUrl: 'https://picsum.photos/120/120?random=51',
    phone: '+92 313 5554444',
    email: 'nadia.h@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=41',
    bio: 'We source authentic nomadic and tribal rugs directly from communities, ensuring fair prices and preserving their craft.',
    specialties: ['Direct Sourcing', 'Authentic Tribal', 'Fair Trade'],
  },
  {
    id: '42',
    name: 'Naeem Bukhari',
    company: 'National Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=52',
    phone: '+92 314 6665555',
    email: 'naeem.b@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=42',
    bio: 'One of the largest manufacturers in Pakistan, supplying both domestic and international markets for over 40 years.',
    specialties: ['Large Manufacturer', 'Domestic Supply', 'International Markets'],
  },
  // O
  {
    id: '43',
    name: 'Osman Khalid',
    company: 'Oriental Knot',
    companyLogoUrl: 'https://picsum.photos/120/120?random=53',
    phone: '+92 315 7776666',
    email: 'osman.k@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=43',
    bio: 'Experts in the art of hand-knotting, producing rugs with exceptionally high knot counts and detailed patterns.',
    specialties: ['Hand-Knotting Experts', 'High Knot Count', 'Detailed Patterns'],
  },
  {
    id: '44',
    name: 'Omar Sharif',
    company: 'Oushak Creations',
    companyLogoUrl: 'https://picsum.photos/120/120?random=54',
    phone: '+92 316 8887777',
    email: 'omar.s@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=44',
    bio: 'Specializing in the production of Pakistani Oushak rugs, known for their soft color palettes and large-scale floral designs.',
    specialties: ['Oushak Rugs', 'Soft Palettes', 'Large-Scale Florals'],
  },
  // P
  {
    id: '45',
    name: 'Pervez Musharraf',
    company: 'Pak-Persian Rugs',
    companyLogoUrl: 'https://picsum.photos/120/120?random=55',
    phone: '+92 317 9998888',
    email: 'pervez.m@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=45',
    bio: 'We produce high-quality reproductions of classic Persian designs, offering the beauty of Iran at a Pakistani price point.',
    specialties: ['Pak-Persian', 'Persian Reproductions', 'Quality & Value'],
  },
  {
    id: '46',
    name: 'Parveen Rana',
    company: 'Pinnacle Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=56',
    phone: '+92 318 1119999',
    email: 'parveen.r@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=46',
    bio: 'Striving for the pinnacle of quality, our workshop produces a limited quantity of exceptionally fine rugs each year.',
    specialties: ['Exceptional Quality', 'Limited Production', 'Fine Rugs'],
  },
  // Q
  {
    id: '47',
    name: 'Qasim Ali',
    company: 'Quality Weavers',
    companyLogoUrl: 'https://picsum.photos/120/120?random=57',
    phone: '+92 320 2221111',
    email: 'qasim.ali@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=47',
    bio: 'Our name says it all. We are committed to a strict quality control process to deliver flawless carpets every time.',
    specialties: ['Quality Control', 'Flawless Weaving', 'Consistency'],
  },
  {
    id: '48',
    name: 'Quratulain Balouch',
    company: 'Q.B. Designs',
    companyLogoUrl: 'https://picsum.photos/120/120?random=58',
    phone: '+92 321 3332222',
    email: 'quratulain.b@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=48',
    bio: 'A contemporary designer bringing a unique, artistic, and musical sensibility to the world of carpet weaving.',
    specialties: ['Artistic Design', 'Contemporary', 'Unique Sensibility'],
  },
  // R
  {
    id: '49',
    name: 'Rashid Mehmood',
    company: 'Royal Carpet House',
    companyLogoUrl: 'https://picsum.photos/120/120?random=59',
    phone: '+92 322 4443333',
    email: 'rashid.m@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=49',
    bio: 'Producers of carpets fit for royalty, specializing in large, palace-sized rugs with intricate designs and gold/silver thread.',
    specialties: ['Palace-Sized Rugs', 'Royal Designs', 'Luxury Materials'],
  },
  {
    id: '50',
    name: 'Rehana Siddiqui',
    company: 'Rug Republic',
    companyLogoUrl: 'https://picsum.photos/120/120?random=60',
    phone: '+92 323 5554444',
    email: 'rehana.s@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=50',
    bio: 'An online-first brand that brings a wide variety of Pakistani rugs directly to consumers around the world.',
    specialties: ['E-Commerce', 'Direct to Consumer', 'Global Reach'],
  },
  // S
  {
    id: '51',
    name: 'Salman Alvi',
    company: 'Sultan Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=61',
    phone: '+92 324 6665555',
    email: 'salman.alvi@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=51',
    bio: 'Specializing in Sultanabad and Heriz designs, we bring the grandeur of classic Persian motifs to life with Pakistani craftsmanship.',
    specialties: ['Sultanabad Designs', 'Heriz Reproductions', 'Classic Grandeur'],
  },
  {
    id: '52',
    name: 'Samina Peerzada',
    company: 'SP Looms',
    companyLogoUrl: 'https://picsum.photos/120/120?random=62',
    phone: '+92 330 7776666',
    email: 'samina.p@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=52',
    bio: 'A celebrated designer creating bespoke rugs that tell a story, weaving together elements of theater, art, and tradition.',
    specialties: ['Bespoke Story Rugs', 'Artistic Weaving', 'Theatrical Designs'],
  },
  // T
  {
    id: '53',
    name: 'Tariq Amin',
    company: 'Tribal Traditions',
    companyLogoUrl: 'https://picsum.photos/120/120?random=63',
    phone: '+92 331 8887777',
    email: 'tariq.amin@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=53',
    bio: 'We specialize in sourcing and selling authentic tribal rugs from all over Pakistan, including Balochi and Pashtun designs.',
    specialties: ['Authentic Tribal', 'Balochi Rugs', 'Pashtun Weaves'],
  },
  {
    id: '54',
    name: 'Tehmina Durrani',
    company: 'Tapestry House',
    companyLogoUrl: 'https://picsum.photos/120/120?random=64',
    phone: '+92 332 9998888',
    email: 'tehmina.d@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=54',
    bio: 'Creating wall-hanging tapestries and pictorial rugs that are true works of art, depicting scenes from Pakistani folklore and history.',
    specialties: ['Wall Tapestries', 'Pictorial Rugs', 'Folklore & History'],
  },
  // U
  {
    id: '55',
    name: 'Umar Saif',
    company: 'Universal Carpet Traders',
    companyLogoUrl: 'https://picsum.photos/120/120?random=65',
    phone: '+92 333 1119999',
    email: 'umar.saif@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=55',
    bio: 'A major trading house that sources and exports a universal range of carpet types, serving wholesalers across the globe.',
    specialties: ['Global Wholesaler', 'Carpet Trading', 'Universal Sourcing'],
  },
  {
    id: '56',
    name: 'Uzma Gillani',
    company: 'Ultimate Weaves',
    companyLogoUrl: 'https://picsum.photos/120/120?random=66',
    phone: '+92 334 2221111',
    email: 'uzma.g@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=56',
    bio: 'We aim to produce the ultimate in luxury and quality, using only the finest materials like pashmina and silk.',
    specialties: ['Ultimate Luxury', 'Pashmina', 'Fine Silk'],
  },
  // V
  {
    id: '57',
    name: 'Vaneeza Ahmed',
    company: 'V-Design Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=67',
    phone: '+92 335 3332222',
    email: 'vaneeza.a@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=57',
    bio: 'A fashion-forward brand creating runway-inspired rug collections that are bold, contemporary, and glamorous.',
    specialties: ['Fashion-Forward', 'Runway Inspired', 'Glamorous Designs'],
  },
  {
    id: '58',
    name: 'Vakas Khan',
    company: 'Village Craft',
    companyLogoUrl: 'https://picsum.photos/120/120?random=68',
    phone: '+92 336 4443333',
    email: 'vakas.k@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=58',
    bio: 'Working with village-based weavers to bring their authentic, rustic, and charming creations to a wider market.',
    specialties: ['Village Weavers', 'Authentic Craft', 'Rustic Charm'],
  },
  // W
  {
    id: '59',
    name: 'Wasim Akram',
    company: 'World Class Weavers',
    companyLogoUrl: 'https://picsum.photos/120/120?random=69',
    phone: '+92 340 5554444',
    email: 'wasim.akram@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=59',
    bio: 'Committed to world-class quality standards, we are an ISO 9001 certified company exporting to premium markets.',
    specialties: ['ISO 9001 Certified', 'Premium Markets', 'Quality Assurance'],
  },
  {
    id: '60',
    name: 'Wajiha Ather',
    company: 'Woven Dreams',
    companyLogoUrl: 'https://picsum.photos/120/120?random=70',
    phone: '+92 341 6665555',
    email: 'wajiha.a@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=60',
    bio: 'We help you weave your dreams into reality with fully customized, bespoke carpets designed to your exact specifications.',
    specialties: ['Custom Designs', 'Bespoke Services', 'Dream Rugs'],
  },
  // X
  {
    id: '61',
    name: 'Xerxes Alam',
    company: 'Xenon Exports',
    companyLogoUrl: 'https://picsum.photos/120/120?random=71',
    phone: '+92 342 7776666',
    email: 'xerxes.a@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=61',
    bio: 'A modern export house using technology to streamline the sourcing and logistics process for international buyers.',
    specialties: ['Tech-Enabled', 'Streamlined Logistics', 'Modern Export'],
  },
  // Y
  {
    id: '62',
    name: 'Yasir Hussain',
    company: 'Yarkand Looms',
    companyLogoUrl: 'https://picsum.photos/120/120?random=72',
    phone: '+92 343 8887777',
    email: 'yasir.h@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=62',
    bio: 'Specializing in designs inspired by the ancient Silk Road, including Yarkand and Kashgar motifs.',
    specialties: ['Silk Road Designs', 'Yarkand Motifs', 'Kashgar Style'],
  },
  {
    id: '63',
    name: 'Yasmin Sheikh',
    company: 'Your Carpet Story',
    companyLogoUrl: 'https://picsum.photos/120/120?random=73',
    phone: '+92 344 9998888',
    email: 'yasmin.s@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=63',
    bio: 'We believe every carpet has a story. We create bespoke rugs that incorporate personal symbols and narratives for our clients.',
    specialties: ['Personalized Rugs', 'Narrative Design', 'Bespoke Storytelling'],
  },
  // Z
  {
    id: '64',
    name: 'Zainab Qayyum',
    company: 'Zainab Carpets',
    companyLogoUrl: 'https://picsum.photos/120/120?random=74',
    phone: '+92 345 1119999',
    email: 'zainab.q@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=64',
    bio: 'A designer-led firm known for its elegant and sophisticated transitional rugs that bridge classic and contemporary styles.',
    specialties: ['Transitional Rugs', 'Elegant Designs', 'Sophisticated Style'],
  },
  {
    id: '65',
    name: 'Zahid Ahmed',
    company: 'Z-Exporters',
    companyLogoUrl: 'https://picsum.photos/120/120?random=75',
    phone: '+92 346 2221111',
    email: 'zahid.ahmed@example.com',
    avatarUrl: 'https://picsum.photos/100/100?random=65',
    bio: 'A reliable and efficient export partner for wholesalers and retailers looking for consistent quality and timely delivery.',
    specialties: ['Reliable Exporter', 'Timely Delivery', 'Wholesale Partner'],
  },
];

export const resourceData: Resource[] = [
  {
    id: '1',
    name: 'EU GSP+ Compliance Guide.pdf',
    categories: ['Trade Regulations', 'Legal Documents'],
    keywords: ['GSP+', 'EU', 'compliance', 'export'],
    summary: 'A comprehensive guide on meeting the compliance requirements for GSP+ status when exporting to the European Union.',
    uploadDate: '2024-06-20',
  },
  {
    id: '2',
    name: 'North American Market Analysis Q2 2024.docx',
    categories: ['Market Analysis', 'Export Data'],
    keywords: ['market', 'analysis', 'USA', 'Canada'],
    summary: 'Quarterly report detailing market size, trends, and consumer preferences for handmade carpets in the US and Canada.',
    uploadDate: '2024-07-01',
  },
  {
    id: '3',
    name: 'Child Labor Eradication Policy.pdf',
    categories: ['Sustainability Reports', 'Legal Documents'],
    keywords: ['sustainability', 'child labor', 'policy', 'ethics'],
    summary: 'Official PCMEA policy document outlining the commitment and procedures to eradicate child labor from the carpet industry supply chain.',
    uploadDate: '2024-05-15',
  },
  {
    id: '4',
    name: 'Natural Dye Techniques Guide.pdf',
    categories: ['Training Materials', 'Sustainability Reports'],
    keywords: ['natural dyes', 'training', 'eco-friendly', 'weaving'],
    summary: 'A practical guide for artisans on using traditional, all-natural dyes for coloring wool and other fibers.',
    uploadDate: '2024-07-05',
  },
  {
    id: '5',
    name: 'PCMEA Annual Report 2023.pdf',
    categories: ['PCMEA Announcements', 'Export Data'],
    keywords: ['annual report', 'PCMEA', 'statistics', '2023'],
    summary: 'The official annual report from PCMEA for the fiscal year 2023, including export statistics and organizational updates.',
    uploadDate: '2024-04-30',
  },
  {
    id: '6',
    name: 'Member Spotlight - Khan Carpets.docx',
    categories: ['Member News'],
    keywords: ['member', 'spotlight', 'interview', 'Khan Carpets'],
    summary: 'An interview with Mr. Ahmed Khan of Khan Carpets International about their success in the European market.',
    uploadDate: '2024-07-10',
  },
  {
    id: '7',
    name: 'Digital Marketing for Exporters.pptx',
    categories: ['Training Materials', 'Industry Trends'],
    keywords: ['digital marketing', 'social media', 'export', 'sales'],
    summary: 'Presentation slides from the recent workshop on leveraging digital marketing and social media to boost international sales.',
    uploadDate: '2024-06-28',
  },
  {
    id: '8',
    name: 'Upcoming Domotex 2025 Info Pack.pdf',
    categories: ['PCMEA Announcements', 'Industry Trends'],
    keywords: ['Domotex', 'trade fair', 'exhibition', 'Germany'],
    summary: 'An information package for members interested in participating in the upcoming Domotex 2025 trade fair in Hannover, Germany.',
    uploadDate: '2024-07-18',
  },
];

export const encyclopediaData: RugEncyclopediaEntry[] = [
  // Persian Rugs
  {
    id: 'p1',
    name: 'Abadeh',
    origin: 'Persia (Iran)',
    description: 'From a village between Isfahan and Shiraz, these rugs are known for a characteristic hexagonal center medallion featuring stylized geometric patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=1',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Hexagonal medallion, geometric patterns' },
  },
  {
    id: 'p2',
    name: 'Ardebil',
    origin: 'Persia (Iran)',
    description: 'Woven in the Ardebil region of northwestern Iran, these rugs often feature geometric and floral designs, sometimes mimicking Caucasian patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=2',
    characteristics: { material: 'Wool on cotton', knot: 'Turkish (symmetrical)', design: 'Geometric, floral, Caucasian influence' },
  },
  {
    id: 'p3',
    name: 'Bakhtiari',
    origin: 'Persia (Iran)',
    description: 'Woven by the Bakhtiari tribe in the Zagros Mountains, these rugs are famous for the "Khesti" or garden panel design, dividing the field into compartments filled with floral or animal motifs.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
    characteristics: { material: 'Wool on cotton', knot: 'Turkish (symmetrical)', design: 'Garden panel (Khesti), floral/animal motifs' },
  },
  {
    id: 'p4',
    name: 'Baluchi',
    origin: 'Persia (Iran) / Afghanistan / Pakistan',
    description: 'Woven by the Baluch nomadic tribes. They often feature prayer designs, rich, dark reds and blues, and geometric motifs.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
    characteristics: { material: 'Wool on wool or cotton', knot: 'Persian (asymmetrical)', design: 'Geometric, prayer designs, dark colors' },
  },
  {
    id: 'p5',
    name: 'Bijar',
    origin: 'Persia (Iran)',
    description: 'Known as the "Iron Rug of Persia" for its extremely dense and durable weaving, done by Kurdish weavers. They typically have bold, geometric, and floral designs.',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    characteristics: { material: 'Wool on cotton', knot: 'Turkish (symmetrical)', design: 'Dense weave, bold geometric and floral' },
  },
  {
    id: 'p6',
    name: 'Gabbeh',
    origin: 'Persia (Iran)',
    description: 'A thick, hand-knotted tribal rug woven by the Qashqai and other tribes, known for its minimalist, abstract, and geometric designs.',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    characteristics: { material: 'Wool on wool', knot: 'Persian/Turkish', design: 'Minimalist, abstract, geometric' },
  },
  {
    id: 'p7',
    name: 'Heriz/Serapi',
    origin: 'Persia (Iran)',
    description: 'From the Heriz region, these feature a distinct, bold, and geometric central medallion.',
    imageUrl: 'https://picsum.photos/600/400?random=7',
    characteristics: { material: 'Wool on cotton', knot: 'Turkish (symmetrical)', design: 'Bold geometric central medallion' },
  },
  {
    id: 'p8',
    name: 'Isfahan',
    origin: 'Persia (Iran)',
    description: 'Finely woven rugs from Isfahan, known for intricate curvilinear designs, high knot density, and elegant floral motifs.',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    characteristics: { material: 'Wool/silk on silk/cotton', knot: 'Persian (asymmetrical)', design: 'Intricate curvilinear, floral motifs' },
  },
  {
    id: 'p9',
    name: 'Kashan',
    origin: 'Persia (Iran)',
    description: 'Originating from Kashan, these rugs are known for their tightly knotted structure, often with a central medallion on a floral field.',
    imageUrl: 'https://picsum.photos/600/400?random=9',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Central medallion, floral field' },
  },
  {
    id: 'p10',
    name: 'Kerman/Kirman',
    origin: 'Persia (Iran)',
    description: 'Known for a wide range of decorative designs, often with graceful floral motifs and pastel colors.',
    imageUrl: 'https://picsum.photos/600/400?random=10',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Graceful floral motifs, pastel colors' },
  },
  {
    id: 'p11',
    name: 'Nain',
    origin: 'Persia (Iran)',
    description: 'High-quality rugs known for their use of fine wool and silk, typically in a characteristic ivory and blue color scheme with a classical central medallion.',
    imageUrl: 'https://picsum.photos/600/400?random=11',
    characteristics: { material: 'Wool/silk on cotton', knot: 'Persian (asymmetrical)', design: 'Ivory/blue scheme, central medallion' },
  },
  {
    id: 'p12',
    name: 'Qum (Qom)',
    origin: 'Persia (Iran)',
    description: 'Famous for very fine, tightly woven rugs often made with silk, featuring a wide range of intricate designs.',
    imageUrl: 'https://picsum.photos/600/400?random=12',
    characteristics: { material: 'Silk on silk/cotton', knot: 'Persian (asymmetrical)', design: 'Very fine, intricate, often silk' },
  },
  {
    id: 'p13',
    name: 'Sultanabad',
    origin: 'Persia (Iran)',
    description: 'Antique Persian carpets from the Arak region known for their curvilinear, all-over floral and geometric designs. Modern Pakistani versions are also common.',
    imageUrl: 'https://picsum.photos/600/400?random=13',
    characteristics: { material: 'Wool on cotton', knot: 'Turkish (symmetrical)', design: 'All-over floral, geometric' },
  },
  {
    id: 'p14',
    name: 'Tabriz',
    origin: 'Persia (Iran)',
    description: 'A major weaving center in Iran, producing a wide variety of high-quality rugs with both geometric and floral designs, including pictorial and hunting scenes.',
    imageUrl: 'https://picsum.photos/600/400?random=14',
    characteristics: { material: 'Wool/silk on cotton/silk', knot: 'Turkish/Persian', design: 'Diverse; geometric, floral, pictorial' },
  },
  {
    id: 'p15',
    name: 'Sarouk',
    origin: 'Persia (Iran)',
    description: 'Historically, these were fine, durable rugs with elegant floral patterns. Modern commercial versions are also available.',
    imageUrl: 'https://picsum.photos/600/400?random=32',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Elegant floral, medallions' },
  },
  {
    id: 'p16',
    name: 'Shiraz',
    origin: 'Persia (Iran)',
    description: 'Bold, tribal-style rugs with geometric motifs and nomadic flair, typically sold from the bazaar in Shiraz.',
    imageUrl: 'https://picsum.photos/600/400?random=33',
    characteristics: { material: 'Wool on wool', knot: 'Persian (asymmetrical)', design: 'Geometric, nomadic, stylized animals' },
  },

  // Afghan Rugs
  {
    id: 'a1',
    name: 'Afghan Kilim',
    origin: 'Afghanistan',
    description: 'Flat-woven rugs known for their geometric designs and vibrant colors.',
    imageUrl: 'https://picsum.photos/600/400?random=15',
    characteristics: { material: 'Wool', knot: 'Flat-weave', design: 'Geometric, vibrant colors' },
  },
  {
    id: 'a2',
    name: 'Bokhara (Afghan)',
    origin: 'Afghanistan',
    description: 'Reproductions of the classic Turkmen Bokhara style, featuring repeating octagonal gul motifs on a deep red field.',
    imageUrl: 'https://picsum.photos/600/400?random=16',
    characteristics: { material: 'Wool on wool/cotton', knot: 'Persian (asymmetrical)', design: 'Repeating guls, deep red field' },
  },
  {
    id: 'a3',
    name: 'Khal Mohammadi',
    origin: 'Afghanistan',
    description: 'Named after a master weaver, these are famous for their dark red backgrounds and distinctive repeating geometric guls.',
    imageUrl: 'https://picsum.photos/600/400?random=17',
    characteristics: { material: 'Wool on wool/cotton', knot: 'Persian (asymmetrical)', design: 'Geometric guls, dark red background' },
  },
  {
    id: 'a4',
    name: 'Shindand/Adrakshan',
    origin: 'Afghanistan',
    description: 'Distinctive rugs with stylized human and animal figures often depicted in narrative scenes.',
    imageUrl: 'https://picsum.photos/600/400?random=18',
    characteristics: { material: 'Wool on wool', knot: 'Persian (asymmetrical)', design: 'Stylized human/animal figures' },
  },
  {
    id: 'a5',
    name: 'War Rugs',
    origin: 'Afghanistan',
    description: 'A modern style that emerged during the Soviet invasion, featuring depictions of military weapons and tanks.',
    imageUrl: 'https://picsum.photos/600/400?random=19',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Military motifs (tanks, guns)' },
  },
  {
    id: 'a6',
    name: 'Ersari',
    origin: 'Afghanistan',
    description: 'Woven by the Ersari Turkmen tribe and often featuring deep reds and large, repeating geometric patterns (guls).',
    imageUrl: 'https://picsum.photos/600/400?random=34',
    characteristics: { material: 'Hand-spun Ghazni wool', knot: 'Asymmetrical', design: 'Large geometric guls, deep reds' },
  },
  {
    id: 'a7',
    name: 'Ghazni',
    origin: 'Afghanistan',
    description: 'High-quality rugs known for their hand-spun Ghazni wool, which can create a unique abrash (color variation) effect.',
    imageUrl: 'https://picsum.photos/600/400?random=35',
    characteristics: { material: 'Hand-spun Ghazni wool', knot: 'Asymmetrical', design: 'Abrash effect, traditional patterns' },
  },

  // Pakistani Rugs
  {
    id: 'pk1',
    name: 'Pak Persian',
    origin: 'Pakistan',
    description: 'High-knot-density rugs inspired by classic Persian designs such as Kashan, Kirman, and Isfahan.',
    imageUrl: 'https://picsum.photos/600/400?random=20',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Classic Persian floral/medallion' },
  },
  {
    id: 'pk2',
    name: 'Chobi (Ziegler)/Peshawar',
    origin: 'Pakistan',
    description: 'Characterized by washed-out, vintage looks, larger-scale designs, and the use of natural dyes, often influenced by Persian carpets.',
    imageUrl: 'https://picsum.photos/600/400?random=21',
    characteristics: { material: 'Hand-spun wool, natural dyes', knot: 'Persian (asymmetrical)', design: 'Large-scale floral, antique wash' },
  },
  {
    id: 'pk3',
    name: 'Jaldar',
    origin: 'Pakistan',
    description: 'Inspired by traditional Sarouk and Yamud designs, featuring rows of diamond-shaped gul motifs.',
    imageUrl: 'https://picsum.photos/600/400?random=22',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Repeating diamond-shaped guls' },
  },
  {
    id: 'pk4',
    name: 'Mori Bokhara',
    origin: 'Pakistan',
    description: 'A commercial name for Pakistani Bokhara rugs, with soft, lustrous pile and Turkmen gul patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=23',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Turkmen guls, soft pile' },
  },
  {
    id: 'pk5',
    name: 'Pak Gabbeh',
    origin: 'Pakistan',
    description: 'Modern Gabbeh-style rugs with contemporary, abstract designs, typically woven with handspun wool and vegetable dyes.',
    imageUrl: 'https://picsum.photos/600/400?random=24',
    characteristics: { material: 'Hand-spun wool', knot: 'Persian (asymmetrical)', design: 'Contemporary, abstract, minimalist' },
  },
  {
    id: 'pk6',
    name: 'Pakistani Caucasian/Kazak',
    origin: 'Pakistan',
    description: 'Reproductions of traditional Caucasian geometric designs, woven with a Turkish knot.',
    imageUrl: 'https://picsum.photos/600/400?random=25',
    characteristics: { material: 'Wool on cotton', knot: 'Turkish (symmetrical)', design: 'Bold geometric patterns, medallions' },
  },
  {
    id: 'pk7',
    name: 'Beljik',
    origin: 'Pakistan',
    description: 'Named after high-quality imported Belgian wool, these rugs are known for fine craftsmanship and intricate geometric or floral patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=36',
    characteristics: { material: 'Fine wool on cotton', knot: 'Persian (asymmetrical)', design: 'Intricate geometric or floral' },
  },
  {
    id: 'pk8',
    name: 'Pakistani Oushak',
    origin: 'Pakistan',
    description: 'Based on the classic Turkish Oushak design, with large, simple geometric and floral patterns and a soft color palette.',
    imageUrl: 'https://picsum.photos/600/400?random=37',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Large-scale geometric/floral' },
  },

  // Indian Rugs
  {
    id: 'in1',
    name: 'Agra',
    origin: 'India',
    description: 'Continuing the Mughal weaving tradition, these feature floral, geometric, and medallion patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=26',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Mughal-inspired floral/geometric' },
  },
  {
    id: 'in2',
    name: 'Dhurries',
    origin: 'India',
    description: 'Reversible, flat-woven rugs made of cotton or wool, known for their colorful geometric patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=27',
    characteristics: { material: 'Cotton or wool', knot: 'Flat-weave', design: 'Geometric, stripes, reversible' },
  },
  {
    id: 'in3',
    name: 'Indo-Gabbeh',
    origin: 'India',
    description: 'Indian-knotted versions of the Persian Gabbeh, often with simplified, contemporary abstract designs.',
    imageUrl: 'https://picsum.photos/600/400?random=28',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Simplified, contemporary abstract' },
  },
  {
    id: 'in4',
    name: 'Indo-Persian',
    origin: 'India',
    description: 'A general term for Indian rugs that reproduce classic Persian patterns like Tabriz, Kerman, and Isfahan.',
    imageUrl: 'https://picsum.photos/600/400?random=29',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Reproductions of classic Persian designs' },
  },
  {
    id: 'in5',
    name: 'Jaipur',
    origin: 'India',
    description: 'A center for high-quality flat-weave dhurries and hand-knotted wool rugs, known for its fine weave and vibrant colors.',
    imageUrl: 'https://picsum.photos/600/400?random=30',
    characteristics: { material: 'Wool or cotton', knot: 'Hand-knotted or flat-weave', design: 'Fine weave, vibrant colors' },
  },
  {
    id: 'in6',
    name: 'Kashmir',
    origin: 'India / Pakistan',
    description: 'Fine, high-quality rugs often made of silk and featuring intricate floral or paisley patterns.',
    imageUrl: 'https://picsum.photos/600/400?random=31',
    characteristics: { material: 'Silk or fine wool', knot: 'Persian (asymmetrical)', design: 'Intricate floral, paisley' },
  },
  {
    id: 'in7',
    name: 'Amritsar',
    origin: 'India',
    description: 'Known for fine-quality, commercially produced rugs, often reproducing classical Persian and Mughal designs with a softer color palette.',
    imageUrl: 'https://picsum.photos/600/400?random=38',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Classical Persian/Mughal, soft colors' },
  },
  {
    id: 'in8',
    name: 'Bhadohi',
    origin: 'India',
    description: 'From a major weaving center in Uttar Pradesh, producing hand-knotted rugs with a wide variety of designs, from traditional Persian to modern.',
    imageUrl: 'https://picsum.photos/600/400?random=39',
    characteristics: { material: 'Wool on cotton', knot: 'Persian (asymmetrical)', design: 'Varied, from traditional to modern' },
  },
];

export const boardOfDirectorsData: BoardMember[] = [
  {
    id: '1',
    name: 'Mr. Aslam Tariq',
    position: 'Chairman',
    company: 'Tariq & Sons Carpets',
    avatarUrl: 'https://picsum.photos/400/600?random=1',
  },
  {
    id: '2',
    name: 'Mr. Javed Akhtar',
    position: 'Senior Vice Chairman',
    company: 'Akhtar Weavers',
    avatarUrl: 'https://picsum.photos/400/600?random=2',
  },
  {
    id: '3',
    name: 'Mrs. Saima Riaz',
    position: 'Vice Chairperson',
    company: 'Riaz Designs',
    avatarUrl: 'https://picsum.photos/400/600?random=3',
  },
  {
    id: '4',
    name: 'Mr. Pervez Khalid',
    position: 'Executive Member',
    company: 'Khalid Exports',
    avatarUrl: 'https://picsum.photos/400/600?random=4',
  },
  {
    id: '5',
    name: 'Mr. Imran Ghafoor',
    position: 'Executive Member',
    company: 'Ghafoor Rugs',
    avatarUrl: 'https://picsum.photos/400/600?random=5',
  },
  {
    id: '6',
    name: 'Ms. Nadia Sheikh',
    position: 'Executive Member',
    company: 'Sheikh Looms',
    avatarUrl: 'https://picsum.photos/400/600?random=6',
  },
];
